config = {
  LAUNCH_LEVEL_EDITOR = false,
  SHOW_DEBUG_SKIP_SCREENS = true,
  SHOW_DIAGNOSTIC_STATS = false,
  MUSIC_VOLUME = 0.13,
  SOUND_VOLUME = 1.0,
  SKIP_SCENE_TRANSITIONS = false,
  SKIP_WORLD_TRANSITIONS = false,
  BACKWARDS_COMPATIBILITY_MODE = false
}
